services:
  koleksiyon-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koleksiyon-yonetim-platformu
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=koleksiyon-yonetim-platformu-secret-key
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    networks:
      - koleksiyon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  koleksiyon-network:
    driver: bridge
    name: koleksiyon-network